id: AE0B63E77
title: Prayer to Karmapa Khakhyab Dorje
type: translation
pechas:
- I8D68F92F
- I31338CC4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:44.245757
  last_modified_at: 2023-01-04 11:51:44.245768
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I8D68F92F/DF48: D7B3
  I31338CC4/7440: D7B3
